In [1]:
import numpy as np

##### Basic Operations with Numpy

In [2]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [3]:
a + 4

array([4, 5, 6, 7])

In [4]:
a * 2

array([0, 2, 4, 6])

In [5]:
# Lets declare another numpy array b

In [6]:
b = np.arange(4, 8)
b

array([4, 5, 6, 7])

In [7]:
#Since a and b has the same number of elements, we can carry out mathematical operations on them

In [8]:
a + b

array([ 4,  6,  8, 10])

In [9]:
a - b

array([-4, -4, -4, -4])

In [10]:
a * b

array([ 0,  5, 12, 21])

In [11]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [12]:
a * np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

In [13]:
np.sin(b)

array([-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ])

In [14]:
np.cos(b)

array([-0.65364362,  0.28366219,  0.96017029,  0.75390225])

In [15]:
np.tan(a)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654])

In [16]:
# Moving on to multidimentional cases. The arithmetic operators are also done element-wise

In [17]:
A = np.arange(0, 9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
#We used the reshape function to shape the resultant array into a 3x3 matrix

In [19]:
B = np.ones((3, 3))

In [20]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
type(B)

numpy.ndarray

In [22]:
B.dtype

dtype('float64')

In [23]:
B.shape

(3, 3)

In [24]:
B.size

9

In [25]:
B.ndim

2

### The Matrix Product

In [26]:
# This kind of product is indicated by the dot() function and the operation is not element-wise

In [27]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [28]:
# Alternatively

In [29]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [30]:
# The matrix product is not commutative. So A*B != B*A

In [31]:
np.dot(B,A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

##### Increment and Decrement Operators

In [32]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [33]:
a += 1

In [34]:
a

array([1, 2, 3, 4])

In [35]:
a -= 1
a

array([0, 1, 2, 3])

In [36]:
a *= 4
a

array([ 0,  4,  8, 12])

In [38]:
a //= 4
a

array([0, 1, 2, 3])

##### Universal Functions

In [39]:
a = np.arange(1, 5)
a

array([1, 2, 3, 4])

In [40]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [41]:
np.sqrt(9)

3.0

In [42]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [43]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

##### Aggregate Functions

In [44]:
# Aggregate functions perform an operation on a set of values an produces a single result from the operation.

In [45]:
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
a.sum()

15.0

In [49]:
a.max()

5.7

In [50]:
a.min()

0.3

In [51]:
a.mean()

3.0

In [52]:
a.std()

2.0079840636817816

In [53]:
a.var()

4.032000000000001

##### Indexing, Slicing and Iterating of items in an array 

In [54]:
# The processes are similar to how we index, slice and iterate in python

In [55]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [56]:
a[-1]

15

In [57]:
a[0]

10

In [58]:
a[-6]

10

In [59]:
a[5]

15

In [61]:
# We can select multiple items at once

In [62]:
a[[1, 3, 4]]

array([11, 13, 14])

In [63]:
# Indexing a bidimentional array

In [64]:
A = np.arange(10, 19).reshape((3,3))

In [65]:
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [66]:
A[1, 0]

13

In [67]:
A[2,2]

18

In [68]:
A[0,0]

10

In [70]:
# Slicing: Helps us get a portion of an array to generate new arrays

In [71]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [72]:
a[1:5]

array([11, 12, 13, 14])

In [73]:
# We can give it an incrementing step pattern

In [74]:
a[1:5:2]

array([11, 13])

In [75]:
# We can clone the array just like in python
a[:]

array([10, 11, 12, 13, 14, 15])

In [76]:
a[::2]

array([10, 12, 14])

In [78]:
# Slicing 2 dimensional arrays

In [79]:
A = np.arange(10, 19).reshape((3,3))

In [80]:
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [81]:
A[0,:]

array([10, 11, 12])

In [82]:
A[1, :]

array([13, 14, 15])

In [83]:
A[0, 0]

10

In [84]:
A[:, 0]

array([10, 13, 16])

In [85]:
A[:, 1]

array([11, 14, 17])

In [86]:
# We can also cut a small size of matrix from the 3x3

In [87]:
A[0:2, 0:2]

array([[10, 11],
       [13, 14]])

In [88]:
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [89]:
A[0:2, 0:1]

array([[10],
       [13]])

In [90]:
A[0:1, 0:1]

array([[10]])

In [91]:
A[1:2, 0:2]

array([[13, 14]])

##### Iterating Over an Array

In [92]:
# In python we use the for construct to iterate over the items in an array.

In [93]:
for i in a:
    print(i)

10
11
12
13
14
15


In [94]:
for row in A:
    print(row)

[10 11 12]
[13 14 15]
[16 17 18]


In [95]:
# For element by element iteration, we use the for loop on A.flat

In [96]:
for item in A.flat:
    print(item)

10
11
12
13
14
15
16
17
18
