In [1]:
import pandas as pd
import numpy as np

# Ndarray: The heart of the Numpy Library

In [33]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [31]:
a.dtype

dtype('int32')

In [4]:
type(a)

numpy.ndarray

In [5]:
a.size

3

In [6]:
a.ndim

1

In [7]:
a.shape

(3,)

In [8]:
b = np.array([[0.3, 2.3], [2.1, 1.0]])
b

array([[0.3, 2.3],
       [2.1, 1. ]])

In [9]:
type(b)

numpy.ndarray

In [10]:
b.dtype

dtype('float64')

In [11]:
b.ndim

2

In [12]:
b.shape

(2, 2)

In [13]:
b.size

4

In [14]:
b.itemsize

8

In [15]:
b.data

In [17]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
c.shape

(2, 3)

In [19]:
c.size

6

In [20]:
c.ndim

2

In [21]:
c.itemsize

4

In [22]:
c.dtype

dtype('int32')

In [23]:
type(c)

numpy.ndarray

In [24]:
d = np.array(((1, 2, 3), (4, 5, 6)))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Types of Data

In [26]:
g = np.array([["a", "b"], ["c", "d"]])
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [27]:
g.dtype

dtype('<U1')

In [28]:
g.dtype.name

'str32'

In [34]:
f = np.array([[1, 2, 3], [4, 5, 6]], dtype=complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [35]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
ex = np.ones((3,3))

In [39]:
ex

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [42]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [43]:
np.arange(0, 12, 0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5])

##### So far we have created only 1D arrays. To create 2D arrays we can go this way...

In [44]:
np.arange(0, 12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

##### The linspace determines the the number of elements into which we want the interval to be split

In [46]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

##### The random function can be used to generate an array with many elements. It is a very powerful function

In [47]:
np.random.random(3)

array([0.85550308, 0.42372592, 0.27555286])

In [48]:
np.random.random(6)

array([0.62144772, 0.20774638, 0.29148524, 0.79653087, 0.6394943 ,
       0.34894214])

##### The randint gets a random number  that is lesser than the argument passed

In [50]:
np.random.randint(6)

4

In [51]:
np.random.randint(100)

72